-- test seeds for users
insert into users (name, email) values ('bturrill0', 'abutner0@domainmarket.com'), ('doleksinski1', 'nagget1@utexas.edu'), ('mhadaway2', 'hsimonnot2@mac.com'), ('anelle3', 'egame3@technorati.com'), ('bhurst4', 'afryd4@discovery.com'), ('epovey5', 'lmecozzi5@ameblo.jp'), ('cgaukroger6', 'dhoy6@sciencedirect.com'), ('twagon7', 'vvater7@pinterest.com'), ('mmissenden8', 'nbuzza8@51.la'), ('sdougherty9', 'wczajka9@foxnews.com'), ('shaberchama', 'cbeamisha@bing.com'), ('crydingb', 'nsweetsurb@freewebs.com'), ('dsmalleyc', 'htaylotc@shutterfly.com'), ('lriolfod', 'wjaneckid@csmonitor.com'), ('halsforde', 'croffe@pen.io'), ('etilliardsf', 'torwinf@mapquest.com'), ('kmarchisog', 'hgoymerg@pinterest.com'), ('jsimisterh', 'lwakerleyh@tumblr.com'), ('klemasneyi', 'ghuddarti@vinaora.com'), ('jchurmsj', 'rmahedyj@topsy.com'), ('dnunsonk', 'rboldtk@issuu.com'), ('wruzekl', 'jhuskl@slashdot.org'), ('wtattersdillm', 'epalkm@sohu.com'), ('mdebischofn', 'ftschieraschen@webeden.co.uk'), ('gstuddardo', 'vmaclachlano@cbslocal.com');
-- test seeds for topics
insert into topics (name) values ('full-range');
insert into topics (name) values ('national');
insert into topics (name) values ('upward-trending');
insert into topics (name) values ('protocol');
insert into topics (name) values ('Assimilated');
insert into topics (name) values ('Virtual');
insert into topics (name) values ('flexibility');
insert into topics (name) values ('Profound');
-- test seeds for resources
insert into resources (user_id, topic_id, url, title, description, created_at) values (6, 3, 'http://istockphoto.com', 'vestibulum aliquet ultrices', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2018-08-21 04:43:29');
insert into resources (user_id, topic_id, url, title, description, created_at) values (22, 1, 'http://pcworld.com', 'vel enim sit amet', 'Aliquam erat volutpat. In congue.', '2020-03-21 15:41:31');
insert into resources (user_id, topic_id, url, title, description, created_at) values (9, 5, 'https://about.com', 'elit', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '2020-09-01 19:53:27');
insert into resources (user_id, topic_id, url, title, description, created_at) values (10, 8, 'https://nhs.uk', 'dignissim vestibulum vestibulum', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2021-04-15 06:29:59');
insert into resources (user_id, topic_id, url, title, description, created_at) values (22, 3, 'https://fda.gov', 'faucibus accumsan', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '2019-05-24 16:46:32');
insert into resources (user_id, topic_id, url, title, description, created_at) values (19, 7, 'https://whitehouse.gov', 'dignissim vestibulum vestibulum ante', 'Pellentesque at nulla. Suspendisse potenti.', '2020-08-09 21:46:37');
insert into resources (user_id, topic_id, url, title, description, created_at) values (7, 7, 'http://dell.com', 'parturient', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2020-12-07 00:37:32');
insert into resources (user_id, topic_id, url, title, description, created_at) values (16, 7, 'http://spotify.com', 'nec nisi', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2020-06-07 00:29:51');
insert into resources (user_id, topic_id, url, title, description, created_at) values (9, 5, 'http://webmd.com', 'sapien sapien non', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', '2018-08-15 00:04:02');
insert into resources (user_id, topic_id, url, title, description, created_at) values (13, 6, 'https://last.fm', 'lectus', 'Etiam justo.', '2020-09-27 15:10:55');
insert into resources (user_id, topic_id, url, title, description, created_at) values (11, 1, 'https://cbsnews.com', 'sit amet turpis elementum', 'Vivamus in felis eu sapien cursus vestibulum.', '2020-01-13 10:50:44');
insert into resources (user_id, topic_id, url, title, description, created_at) values (20, 2, 'http://sun.com', 'amet turpis', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '2020-02-15 12:07:32');
insert into resources (user_id, topic_id, url, title, description, created_at) values (1, 5, 'http://nature.com', 'praesent', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2021-10-28 12:18:38');
insert into resources (user_id, topic_id, url, title, description, created_at) values (17, 4, 'https://si.edu', 'posuere cubilia', 'Morbi ut odio.', '2018-03-07 05:53:19');
insert into resources (user_id, topic_id, url, title, description, created_at) values (10, 6, 'http://wp.com', 'porttitor', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '2018-07-28 16:14:47');
insert into resources (user_id, topic_id, url, title, description, created_at) values (1, 7, 'https://springer.com', 'ut massa', 'Aliquam erat volutpat. In congue.', '2019-01-16 15:26:14');
insert into resources (user_id, topic_id, url, title, description, created_at) values (19, 8, 'https://yolasite.com', 'in porttitor pede', 'Aliquam erat volutpat. In congue. Etiam justo.', '2021-06-29 14:06:48');
insert into resources (user_id, topic_id, url, title, description, created_at) values (12, 6, 'https://etsy.com', 'luctus nec molestie', 'Ut at dolor quis odio consequat varius. Integer ac leo.', '2021-02-05 06:23:03');
insert into resources (user_id, topic_id, url, title, description, created_at) values (21, 2, 'http://thetimes.co.uk', 'etiam faucibus', 'Quisque id justo sit amet sapien dignissim vestibulum.', '2018-05-18 16:17:54');
insert into resources (user_id, topic_id, url, title, description, created_at) values (18, 8, 'http://com.com', 'quam nec dui', 'Fusce posuere felis sed lacus.', '2018-05-08 18:05:30');
insert into resources (user_id, topic_id, url, title, description, created_at) values (19, 7, 'http://jimdo.com', 'id', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2019-05-05 02:34:50');
insert into resources (user_id, topic_id, url, title, description, created_at) values (22, 7, 'https://squidoo.com', 'lectus in', 'Aliquam non mauris. Morbi non lectus.', '2020-05-20 21:55:15');
insert into resources (user_id, topic_id, url, title, description, created_at) values (18, 5, 'https://mtv.com', 'volutpat', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2020-09-07 11:33:09');
insert into resources (user_id, topic_id, url, title, description, created_at) values (17, 4, 'http://japanpost.jp', 'nisl duis', 'Nullam molestie nibh in lectus.', '2019-12-31 22:41:43');
insert into resources (user_id, topic_id, url, title, description, created_at) values (7, 6, 'https://bizjournals.com', 'et tempus semper est', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2021-05-11 18:20:45');
insert into resources (user_id, topic_id, url, title, description, created_at) values (7, 2, 'http://bizjournals.com', 'enim', 'Duis mattis egestas metus. Aenean fermentum.', '2019-05-03 17:05:09');
insert into resources (user_id, topic_id, url, title, description, created_at) values (17, 2, 'http://myspace.com', 'massa', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2021-06-20 00:35:11');
insert into resources (user_id, topic_id, url, title, description, created_at) values (2, 3, 'http://ameblo.jp', 'duis consequat dui nec', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '2021-08-26 17:39:12');
insert into resources (user_id, topic_id, url, title, description, created_at) values (21, 2, 'https://cargocollective.com', 'etiam pretium iaculis', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2018-10-18 15:39:38');
insert into resources (user_id, topic_id, url, title, description, created_at) values (5, 3, 'https://amazon.co.jp', 'eleifend donec ut', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2021-11-08 12:24:22');
insert into resources (user_id, topic_id, url, title, description, created_at) values (17, 4, 'http://google.ca', 'in ante', 'Morbi a ipsum. Integer a nibh.', '2021-04-12 10:24:19');
insert into resources (user_id, topic_id, url, title, description, created_at) values (13, 6, 'https://myspace.com', 'vestibulum ac est', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2021-01-13 20:09:19');
insert into resources (user_id, topic_id, url, title, description, created_at) values (3, 2, 'http://imageshack.us', 'in faucibus orci', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2019-03-28 09:29:00');
insert into resources (user_id, topic_id, url, title, description, created_at) values (19, 2, 'https://yellowpages.com', 'pede', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '2018-11-12 20:43:14');
insert into resources (user_id, topic_id, url, title, description, created_at) values (11, 6, 'https://php.net', 'ligula', 'Nulla suscipit ligula in lacus.', '2021-01-05 03:07:18');
insert into resources (user_id, topic_id, url, title, description, created_at) values (8, 3, 'http://yale.edu', 'eget', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2021-07-03 04:29:32');
insert into resources (user_id, topic_id, url, title, description, created_at) values (17, 5, 'https://miibeian.gov.cn', 'consequat', 'Praesent blandit. Nam nulla.', '2021-09-24 06:41:44');
insert into resources (user_id, topic_id, url, title, description, created_at) values (19, 5, 'https://hp.com', 'eu sapien cursus', 'Nulla ac enim.', '2018-05-09 01:43:12');
insert into resources (user_id, topic_id, url, title, description, created_at) values (18, 8, 'http://plala.or.jp', 'blandit non', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', '2018-04-28 03:21:32');
insert into resources (user_id, topic_id, url, title, description, created_at) values (17, 6, 'http://google.nl', 'lectus vestibulum quam sapien', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '2021-11-20 15:30:38');
insert into resources (user_id, topic_id, url, title, description, created_at) values (13, 2, 'http://amazon.co.jp', 'id mauris', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '2020-09-15 00:42:35');
insert into resources (user_id, topic_id, url, title, description, created_at) values (15, 3, 'https://mac.com', 'fusce consequat', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-12-07 21:37:00');
insert into resources (user_id, topic_id, url, title, description, created_at) values (14, 1, 'https://umich.edu', 'parturient', 'Morbi a ipsum. Integer a nibh.', '2020-01-26 12:28:23');
insert into resources (user_id, topic_id, url, title, description, created_at) values (5, 5, 'https://chron.com', 'ultrices', 'Aliquam erat volutpat. In congue. Etiam justo.', '2021-04-05 13:40:22');
insert into resources (user_id, topic_id, url, title, description, created_at) values (12, 8, 'http://princeton.edu', 'pede', 'Nunc purus.', '2021-11-23 18:55:19');
insert into resources (user_id, topic_id, url, title, description, created_at) values (7, 5, 'https://squarespace.com', 'mattis', 'Pellentesque eget nunc.', '2021-04-27 17:51:44');
insert into resources (user_id, topic_id, url, title, description, created_at) values (3, 5, 'http://slashdot.org', 'vel augue vestibulum ante', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2018-07-14 18:43:48');
insert into resources (user_id, topic_id, url, title, description, created_at) values (18, 4, 'http://unesco.org', 'suspendisse potenti nullam porttitor', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2021-12-20 14:20:32');
insert into resources (user_id, topic_id, url, title, description, created_at) values (22, 2, 'http://baidu.com', 'at', 'Phasellus in felis.', '2021-06-13 12:47:35');
insert into resources (user_id, topic_id, url, title, description, created_at) values (21, 5, 'https://cpanel.net', 'erat vestibulum sed', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-12-12 18:28:36');
-- test seeds for user_likes
insert into user_likes (resource_id, user_id, liked_at) values (40, 23, '2022-01-29 17:34:05');
insert into user_likes (resource_id, user_id, liked_at) values (9, 8, '2021-02-09 08:33:17');
insert into user_likes (resource_id, user_id, liked_at) values (10, 18, '2019-01-28 22:19:10');
insert into user_likes (resource_id, user_id, liked_at) values (45, 19, '2018-11-02 17:56:29');
insert into user_likes (resource_id, user_id, liked_at) values (42, 22, '2019-07-30 23:14:01');
insert into user_likes (resource_id, user_id, liked_at) values (50, 15, '2018-09-04 02:16:00');
insert into user_likes (resource_id, user_id, liked_at) values (35, 24, '2019-01-15 13:11:22');
insert into user_likes (resource_id, user_id, liked_at) values (45, 23, '2020-07-15 18:53:14');
insert into user_likes (resource_id, user_id, liked_at) values (41, 3, '2020-01-13 15:45:13');
insert into user_likes (resource_id, user_id, liked_at) values (39, 14, '2019-06-09 19:30:14');
insert into user_likes (resource_id, user_id, liked_at) values (2, 7, '2021-07-09 00:52:38');
insert into user_likes (resource_id, user_id, liked_at) values (37, 3, '2022-01-20 23:06:47');
insert into user_likes (resource_id, user_id, liked_at) values (18, 15, '2018-10-28 08:10:53');
insert into user_likes (resource_id, user_id, liked_at) values (36, 1, '2020-11-04 06:42:18');
insert into user_likes (resource_id, user_id, liked_at) values (31, 6, '2019-12-10 03:07:37');
insert into user_likes (resource_id, user_id, liked_at) values (13, 5, '2021-10-17 02:24:58');
insert into user_likes (resource_id, user_id, liked_at) values (3, 16, '2020-11-26 01:23:04');
insert into user_likes (resource_id, user_id, liked_at) values (32, 1, '2019-10-30 22:59:06');
insert into user_likes (resource_id, user_id, liked_at) values (39, 18, '2022-01-12 08:57:20');
insert into user_likes (resource_id, user_id, liked_at) values (46, 7, '2021-04-11 23:06:23');
insert into user_likes (resource_id, user_id, liked_at) values (22, 6, '2018-04-01 09:45:21');
insert into user_likes (resource_id, user_id, liked_at) values (13, 22, '2021-11-09 09:36:16');
insert into user_likes (resource_id, user_id, liked_at) values (30, 6, '2021-06-06 03:02:42');
insert into user_likes (resource_id, user_id, liked_at) values (49, 6, '2019-09-25 22:13:06');
insert into user_likes (resource_id, user_id, liked_at) values (13, 8, '2020-03-28 10:00:17');
insert into user_likes (resource_id, user_id, liked_at) values (32, 7, '2020-01-25 15:41:16');
insert into user_likes (resource_id, user_id, liked_at) values (48, 7, '2021-03-14 09:36:25');
insert into user_likes (resource_id, user_id, liked_at) values (49, 17, '2020-10-20 02:57:49');
insert into user_likes (resource_id, user_id, liked_at) values (27, 3, '2021-04-24 10:28:09');
insert into user_likes (resource_id, user_id, liked_at) values (21, 11, '2018-10-13 09:52:30');
insert into user_likes (resource_id, user_id, liked_at) values (18, 9, '2018-05-23 09:56:52');
insert into user_likes (resource_id, user_id, liked_at) values (23, 19, '2021-10-19 15:06:07');
insert into user_likes (resource_id, user_id, liked_at) values (36, 8, '2019-10-24 13:02:07');
insert into user_likes (resource_id, user_id, liked_at) values (39, 5, '2022-02-01 21:18:34');
insert into user_likes (resource_id, user_id, liked_at) values (20, 3, '2021-10-30 07:40:43');
insert into user_likes (resource_id, user_id, liked_at) values (45, 18, '2018-11-01 18:27:07');
insert into user_likes (resource_id, user_id, liked_at) values (15, 11, '2018-06-21 02:12:42');
insert into user_likes (resource_id, user_id, liked_at) values (38, 16, '2019-09-29 07:14:05');
insert into user_likes (resource_id, user_id, liked_at) values (25, 14, '2020-12-18 21:24:39');
insert into user_likes (resource_id, user_id, liked_at) values (19, 21, '2020-06-27 10:58:32');
insert into user_likes (resource_id, user_id, liked_at) values (4, 13, '2018-02-28 10:17:16');
insert into user_likes (resource_id, user_id, liked_at) values (12, 14, '2018-12-17 10:48:36');
insert into user_likes (resource_id, user_id, liked_at) values (11, 6, '2019-06-17 19:54:08');
insert into user_likes (resource_id, user_id, liked_at) values (17, 13, '2020-05-07 12:02:36');
insert into user_likes (resource_id, user_id, liked_at) values (23, 21, '2021-01-01 07:24:29');
insert into user_likes (resource_id, user_id, liked_at) values (36, 2, '2020-07-27 22:43:33');
insert into user_likes (resource_id, user_id, liked_at) values (11, 10, '2020-03-04 09:41:28');
insert into user_likes (resource_id, user_id, liked_at) values (32, 7, '2018-07-28 11:24:04');
insert into user_likes (resource_id, user_id, liked_at) values (29, 9, '2021-11-15 19:06:37');
insert into user_likes (resource_id, user_id, liked_at) values (44, 10, '2022-02-06 14:44:07');
insert into user_likes (resource_id, user_id, liked_at) values (43, 25, '2020-03-11 05:32:18');
insert into user_likes (resource_id, user_id, liked_at) values (26, 8, '2021-07-01 02:50:13');
insert into user_likes (resource_id, user_id, liked_at) values (26, 14, '2018-03-19 05:52:03');
insert into user_likes (resource_id, user_id, liked_at) values (24, 19, '2020-03-16 12:44:34');
insert into user_likes (resource_id, user_id, liked_at) values (32, 21, '2021-08-31 11:32:38');
insert into user_likes (resource_id, user_id, liked_at) values (27, 23, '2018-10-14 05:39:36');
insert into user_likes (resource_id, user_id, liked_at) values (25, 24, '2018-05-12 07:11:44');
insert into user_likes (resource_id, user_id, liked_at) values (30, 17, '2018-10-11 18:29:48');
insert into user_likes (resource_id, user_id, liked_at) values (9, 21, '2019-05-20 19:05:27');
insert into user_likes (resource_id, user_id, liked_at) values (24, 5, '2021-08-29 10:29:08');
insert into user_likes (resource_id, user_id, liked_at) values (46, 6, '2018-08-05 00:18:23');
insert into user_likes (resource_id, user_id, liked_at) values (9, 12, '2019-09-02 12:51:20');
insert into user_likes (resource_id, user_id, liked_at) values (4, 1, '2019-01-09 14:45:44');
insert into user_likes (resource_id, user_id, liked_at) values (23, 15, '2021-09-03 14:31:49');
insert into user_likes (resource_id, user_id, liked_at) values (42, 1, '2019-04-17 21:47:06');
insert into user_likes (resource_id, user_id, liked_at) values (39, 22, '2018-02-18 16:18:23');
insert into user_likes (resource_id, user_id, liked_at) values (44, 25, '2021-11-13 07:07:05');
insert into user_likes (resource_id, user_id, liked_at) values (25, 11, '2019-05-03 19:18:55');
insert into user_likes (resource_id, user_id, liked_at) values (43, 18, '2021-02-11 17:32:36');
insert into user_likes (resource_id, user_id, liked_at) values (19, 22, '2019-05-31 15:14:19');
insert into user_likes (resource_id, user_id, liked_at) values (5, 9, '2019-04-15 10:06:34');
insert into user_likes (resource_id, user_id, liked_at) values (10, 3, '2018-12-09 13:07:35');
insert into user_likes (resource_id, user_id, liked_at) values (27, 22, '2019-01-16 01:17:54');
insert into user_likes (resource_id, user_id, liked_at) values (11, 14, '2019-07-17 06:30:53');
insert into user_likes (resource_id, user_id, liked_at) values (17, 5, '2018-12-27 08:01:38');
insert into user_likes (resource_id, user_id, liked_at) values (33, 20, '2018-02-14 14:33:27');
insert into user_likes (resource_id, user_id, liked_at) values (25, 3, '2021-10-24 05:46:57');
insert into user_likes (resource_id, user_id, liked_at) values (44, 15, '2019-08-07 17:47:30');
insert into user_likes (resource_id, user_id, liked_at) values (38, 12, '2020-06-24 10:02:44');
insert into user_likes (resource_id, user_id, liked_at) values (25, 6, '2020-01-04 00:42:13');
insert into user_likes (resource_id, user_id, liked_at) values (35, 25, '2020-12-26 00:44:59');
insert into user_likes (resource_id, user_id, liked_at) values (35, 17, '2019-09-13 01:36:28');
insert into user_likes (resource_id, user_id, liked_at) values (16, 19, '2018-07-27 11:21:19');
insert into user_likes (resource_id, user_id, liked_at) values (23, 19, '2021-04-09 23:35:55');
insert into user_likes (resource_id, user_id, liked_at) values (6, 19, '2019-01-30 01:42:49');
insert into user_likes (resource_id, user_id, liked_at) values (47, 16, '2021-01-17 19:03:47');
insert into user_likes (resource_id, user_id, liked_at) values (12, 16, '2019-08-04 19:18:05');
insert into user_likes (resource_id, user_id, liked_at) values (39, 16, '2022-01-27 19:31:55');
insert into user_likes (resource_id, user_id, liked_at) values (25, 6, '2021-09-20 15:54:12');
insert into user_likes (resource_id, user_id, liked_at) values (30, 12, '2018-11-09 21:35:49');
insert into user_likes (resource_id, user_id, liked_at) values (29, 21, '2019-02-19 15:49:50');
insert into user_likes (resource_id, user_id, liked_at) values (43, 15, '2020-07-27 23:00:13');
insert into user_likes (resource_id, user_id, liked_at) values (8, 3, '2021-05-24 13:45:08');
insert into user_likes (resource_id, user_id, liked_at) values (13, 12, '2020-11-12 13:50:47');
insert into user_likes (resource_id, user_id, liked_at) values (37, 12, '2019-01-15 15:17:55');
insert into user_likes (resource_id, user_id, liked_at) values (10, 4, '2018-12-25 16:37:42');
insert into user_likes (resource_id, user_id, liked_at) values (3, 21, '2020-03-10 01:57:43');
insert into user_likes (resource_id, user_id, liked_at) values (27, 4, '2019-08-04 10:15:35');
insert into user_likes (resource_id, user_id, liked_at) values (49, 7, '2020-08-30 19:01:40');
insert into user_likes (resource_id, user_id, liked_at) values (29, 9, '2019-03-12 09:41:48');
-- test seeds for resource_comments
insert into resource_comments (resource_id, user_id, comment, liked_at) values (49, 17, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-01-13 14:45:47');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (2, 20, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2020-10-17 09:58:44');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (19, 19, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2020-07-29 22:44:15');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (5, 2, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2020-01-21 14:37:34');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (16, 2, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-01-15 08:38:22');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (22, 19, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2020-11-13 22:08:39');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (48, 20, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2020-12-13 19:16:28');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (30, 3, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2018-09-15 03:06:26');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (12, 23, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2020-10-15 00:09:17');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (27, 7, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2021-07-10 07:08:36');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (27, 9, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2021-12-03 02:28:14');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (11, 13, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2019-09-27 08:35:21');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (42, 22, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2020-01-17 03:57:36');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (23, 11, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2019-10-05 03:26:41');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (40, 6, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2019-04-07 22:27:43');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (38, 18, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2018-10-20 18:06:20');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (30, 22, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2019-01-20 06:19:51');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (30, 6, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2020-10-05 12:44:28');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (19, 8, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2018-04-17 23:37:21');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (48, 4, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2019-04-29 05:19:15');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (23, 14, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2021-11-14 19:27:36');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (40, 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2021-02-06 00:41:52');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (19, 12, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-12-30 08:00:04');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (14, 9, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2019-01-12 01:38:54');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (2, 2, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2020-06-30 05:54:42');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (30, 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2021-10-18 22:26:35');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (26, 19, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-01-12 08:54:45');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (44, 6, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2019-06-05 11:42:19');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (48, 11, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2021-04-17 17:31:00');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (4, 18, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-10-30 18:08:10');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (26, 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2021-07-31 02:35:10');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (47, 24, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-02-15 05:30:00');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (43, 20, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2019-05-06 07:12:10');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (23, 15, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2020-12-18 09:59:31');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (22, 8, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2021-09-21 19:26:24');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (41, 12, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2019-07-13 22:48:17');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (7, 12, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2021-09-17 04:38:07');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (12, 12, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2018-12-24 13:04:27');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (5, 2, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-06-18 11:44:37');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (39, 5, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2018-11-12 04:53:48');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (1, 17, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2018-05-31 11:49:09');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (37, 20, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2019-05-17 20:06:38');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (33, 14, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2021-06-05 08:36:32');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (28, 4, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2019-02-18 14:27:55');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (38, 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2019-11-01 02:06:57');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (7, 8, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2019-10-24 15:25:09');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (16, 19, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2021-11-04 16:32:36');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (26, 9, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2020-03-31 09:14:58');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (5, 3, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2021-01-22 05:26:14');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (45, 11, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2021-09-12 22:29:57');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (45, 16, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2018-05-07 02:43:57');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (49, 19, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2021-03-04 10:49:26');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (37, 2, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2021-07-01 17:31:19');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (23, 25, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2020-07-22 11:47:13');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (48, 10, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2019-02-08 18:08:50');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (22, 23, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2019-11-18 22:56:52');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (18, 12, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2018-06-23 15:46:29');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (16, 23, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-09-03 01:42:31');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (42, 3, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2021-11-13 11:59:04');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (6, 12, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2019-05-29 02:09:25');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (46, 19, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2020-01-16 07:52:54');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (36, 20, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2018-03-10 20:51:32');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (24, 25, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2019-05-29 09:19:58');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (10, 3, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2021-07-21 19:09:44');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (21, 2, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2020-04-19 14:43:35');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (6, 3, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-02-12 06:54:29');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (23, 3, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2018-04-17 19:51:56');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (25, 10, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2018-07-16 12:59:07');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (24, 25, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2019-10-12 17:24:10');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (2, 8, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2019-12-04 20:56:35');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (7, 1, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2019-07-09 16:46:17');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (43, 25, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2021-01-17 17:09:28');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (4, 22, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2018-11-18 03:38:45');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (37, 20, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2020-09-25 19:06:52');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (32, 4, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-04-07 18:08:16');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (6, 2, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2018-07-10 02:48:53');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (23, 12, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2019-12-26 08:58:27');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (20, 3, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2018-05-27 20:23:49');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (37, 14, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-08-09 17:06:33');
insert into resource_comments (resource_id, user_id, comment, liked_at) values (20, 15, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2020-01-01 03:16:42');
