-- dummy data generated at mockaroo.com

-- test seeds for users
insert into users (name, email, password) values ('bturrill0', 'abutner0@domainmarket.com', 'password'), ('doleksinski1', 'nagget1@utexas.edu', 'password'), ('mhadaway2', 'hsimonnot2@mac.com', 'password'), ('anelle3', 'egame3@technorati.com', 'password'), ('bhurst4', 'afryd4@discovery.com', 'password'), ('epovey5', 'lmecozzi5@ameblo.jp', 'password'), ('cgaukroger6', 'dhoy6@sciencedirect.com', 'password'), ('twagon7', 'vvater7@pinterest.com', 'password'), ('mmissenden8', 'nbuzza8@51.la', 'password'), ('sdougherty9', 'wczajka9@foxnews.com', 'password'), ('shaberchama', 'cbeamisha@bing.com', 'password'), ('crydingb', 'nsweetsurb@freewebs.com', 'password'), ('dsmalleyc', 'htaylotc@shutterfly.com', 'password'), ('lriolfod', 'wjaneckid@csmonitor.com', 'password'), ('halsforde', 'croffe@pen.io', 'password'), ('etilliardsf', 'torwinf@mapquest.com', 'password'), ('kmarchisog', 'hgoymerg@pinterest.com', 'password'), ('jsimisterh', 'lwakerleyh@tumblr.com', 'password'), ('klemasneyi', 'ghuddarti@vinaora.com', 'password'), ('jchurmsj', 'rmahedyj@topsy.com', 'password'), ('dnunsonk', 'rboldtk@issuu.com', 'password'), ('wruzekl', 'jhuskl@slashdot.org', 'password'), ('wtattersdillm', 'epalkm@sohu.com', 'password'), ('mdebischofn', 'ftschieraschen@webeden.co.uk', 'password'), ('gstuddardo', 'vmaclachlano@cbslocal.com', 'password');

-- test seeds for resources
insert into resources (user_id, topic, url, title, description, created_at) values (4, 'SASS', 'https://icio.us/duis/bibendum/morbi/non/quam/nec.xml', 'benchmark', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', '1589412958000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'JavaScript', 'https://smh.com.au/nisl.html', 'Managed', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', '1582589865000');
insert into resources (user_id, topic, url, title, description, created_at) values (1, 'Python', 'https://ox.ac.uk/elit/proin/interdum.png', 'User-friendly', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '1603781864000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'CSS', 'http://shop-pro.jp/elementum/ligula/vehicula.js', 'reciprocal', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '1573691527000');
insert into resources (user_id, topic, url, title, description, created_at) values (16, 'PHP', 'https://hud.gov/sed/tristique/in.aspx', '24/7', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', '1579212108000');
insert into resources (user_id, topic, url, title, description, created_at) values (11, 'Python', 'http://nyu.edu/mauris/morbi.html', 'didactic', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', '1553988669000');
insert into resources (user_id, topic, url, title, description, created_at) values (14, 'PHP', 'https://instagram.com/eu.png', 'explicit', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '1570199591000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'Other', 'https://nih.gov/rhoncus/dui/vel/sem/sed/sagittis/nam.html', 'zero administration', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '1643182489000');
insert into resources (user_id, topic, url, title, description, created_at) values (12, 'HTML', 'https://themeforest.net/posuere/cubilia.js', 'background', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', '1543404030000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'Python', 'http://china.com.cn/morbi/sem.xml', 'middleware', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '1637023390000');
insert into resources (user_id, topic, url, title, description, created_at) values (20, 'PHP', 'http://epa.gov/vivamus.xml', 'Digitized', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '1613202800000');
insert into resources (user_id, topic, url, title, description, created_at) values (16, 'JavaScript', 'https://google.ca/ut/at/dolor/quis/odio/consequat.html', 'Persevering', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '1600937606000');
insert into resources (user_id, topic, url, title, description, created_at) values (18, 'Java', 'https://bloomberg.com/vestibulum/sed/magna/at.json', 'scalable', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', '1601100813000');
insert into resources (user_id, topic, url, title, description, created_at) values (16, 'JavaScript', 'http://360.cn/at.html', 'implementation', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '1543718475000');
insert into resources (user_id, topic, url, title, description, created_at) values (24, 'HTML', 'https://netscape.com/odio/donec/vitae.jpg', 'Intuitive', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '1605549877000');
insert into resources (user_id, topic, url, title, description, created_at) values (22, 'SASS', 'https://nba.com/eget/elit/sodales/scelerisque/mauris/sit/amet.json', 'well-modulated', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '1580039928000');
insert into resources (user_id, topic, url, title, description, created_at) values (12, 'HTML', 'http://kickstarter.com/lectus/aliquam.jsp', 'multimedia', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '1642494179000');
insert into resources (user_id, topic, url, title, description, created_at) values (1, 'Python', 'https://mapy.cz/odio/porttitor.jpg', 'array', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '1550477961000');
insert into resources (user_id, topic, url, title, description, created_at) values (5, 'Python', 'http://youtu.be/hendrerit/at/vulputate/vitae.png', 'pricing structure', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '1585641230000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'Other', 'https://jigsy.com/at/nibh/in/hac/habitasse.html', 'utilisation', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '1626413872000');
insert into resources (user_id, topic, url, title, description, created_at) values (9, 'HTML', 'http://jugem.jp/luctus/et.aspx', 'software', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', '1574647244000');
insert into resources (user_id, topic, url, title, description, created_at) values (25, 'CSS', 'http://netlog.com/rhoncus/aliquet/pulvinar.png', 'motivating', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '1588123773000');
insert into resources (user_id, topic, url, title, description, created_at) values (22, 'Other', 'https://sogou.com/ac/enim/in/tempor/turpis.xml', 'functionalities', 'Nulla mollis molestie lorem. Quisque ut erat.', '1545338381000');
insert into resources (user_id, topic, url, title, description, created_at) values (9, 'SASS', 'https://over-blog.com/a/libero/nam/dui/proin/leo/odio.png', 'Cross-platform', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '1644604377000');
insert into resources (user_id, topic, url, title, description, created_at) values (19, 'Other', 'https://com.com/quis/orci/nullam/molestie/nibh.png', 'bifurcated', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '1539173837000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'PHP', 'http://parallels.com/a/suscipit/nulla/elit/ac/nulla.json', 'local', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '1539584643000');
insert into resources (user_id, topic, url, title, description, created_at) values (4, 'Java', 'http://parallels.com/sapien/dignissim/vestibulum/vestibulum/ante.json', 'Vision-oriented', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '1610370133000');
insert into resources (user_id, topic, url, title, description, created_at) values (15, 'Other', 'https://ycombinator.com/massa/tempor/convallis/nulla/neque.html', 'Persevering', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '1570225348000');
insert into resources (user_id, topic, url, title, description, created_at) values (23, 'Java', 'https://livejournal.com/suspendisse/potenti/cras/in/purus.aspx', 'Persevering', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '1623718737000');
insert into resources (user_id, topic, url, title, description, created_at) values (6, 'PHP', 'http://cyberchimps.com/pellentesque/volutpat/dui/maecenas.jpg', 'parallelism', 'Morbi a ipsum. Integer a nibh.', '1609272176000');
insert into resources (user_id, topic, url, title, description, created_at) values (22, 'HTML', 'http://wsj.com/egestas/metus.json', 'Re-engineered', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '1579021685000');
insert into resources (user_id, topic, url, title, description, created_at) values (24, 'JavaScript', 'http://miibeian.gov.cn/eget/eros/elementum/pellentesque/quisque/porta.jpg', 'algorithm', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '1548330105000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'CSS', 'http://cbc.ca/habitasse.png', 'process improvement', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', '1581513547000');
insert into resources (user_id, topic, url, title, description, created_at) values (23, 'Java', 'https://youku.com/ante/ipsum/primis.jpg', 'Versatile', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '1612203291000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'Java', 'http://vistaprint.com/purus.xml', 'scalable', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '1581976697000');
insert into resources (user_id, topic, url, title, description, created_at) values (18, 'HTML', 'https://jiathis.com/ut.jpg', 'multi-tasking', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '1571308395000');
insert into resources (user_id, topic, url, title, description, created_at) values (18, 'HTML', 'https://aboutads.info/velit/id.png', 'Diverse', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '1591020279000');
insert into resources (user_id, topic, url, title, description, created_at) values (9, 'PHP', 'http://hao123.com/quam/nec/dui/luctus/rutrum.jpg', 'hardware', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '1623961300000');
insert into resources (user_id, topic, url, title, description, created_at) values (6, 'JavaScript', 'https://samsung.com/ullamcorper/purus/sit/amet/nulla.xml', 'Future-proofed', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '1557616526000');
insert into resources (user_id, topic, url, title, description, created_at) values (10, 'PHP', 'https://technorati.com/curabitur/in/libero/ut.aspx', 'discrete', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '1571004133000');
insert into resources (user_id, topic, url, title, description, created_at) values (17, 'CSS', 'http://google.de/sollicitudin.jpg', 'web-enabled', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '1632780174000');
insert into resources (user_id, topic, url, title, description, created_at) values (22, 'Java', 'http://ibm.com/massa/volutpat/convallis/morbi/odio/odio/elementum.js', 'Team-oriented', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '1639037877000');
insert into resources (user_id, topic, url, title, description, created_at) values (23, 'Python', 'http://house.gov/pede/justo/eu/massa/donec/dapibus.aspx', 'pricing structure', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '1601050720000');
insert into resources (user_id, topic, url, title, description, created_at) values (18, 'PHP', 'https://sun.com/augue/vel/accumsan.aspx', 'Focused', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '1537904186000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'PHP', 'http://csmonitor.com/quam.html', 'application', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '1581670358000');
insert into resources (user_id, topic, url, title, description, created_at) values (6, 'Java', 'https://ezinearticles.com/vel/est/donec/odio/justo/sollicitudin/ut.jsp', 'Object-based', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '1585550592000');
insert into resources (user_id, topic, url, title, description, created_at) values (8, 'PHP', 'https://linkedin.com/sit/amet/lobortis/sapien/sapien/non/mi.json', 'Assimilated', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', '1543570724000');
insert into resources (user_id, topic, url, title, description, created_at) values (16, 'HTML', 'http://dion.ne.jp/ligula/nec.js', 'Assimilated', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '1615811601000');
insert into resources (user_id, topic, url, title, description, created_at) values (6, 'Java', 'https://g.co/pede/venenatis/non/sodales/sed.xml', 'matrix', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '1578313174000');
insert into resources (user_id, topic, url, title, description, created_at) values (23, 'Other', 'https://twitter.com/parturient.html', 'utilisation', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '1572947992000');
insert into resources (user_id, topic, url, title, description, created_at) values (10, 'Other', 'https://bbc.co.uk/commodo/vulputate/justo.jsp', 'Devolved', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '1630226535000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'Java', 'https://boston.com/curabitur/gravida/nisi/at/nibh.jpg', 'user-facing', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '1561484488000');
insert into resources (user_id, topic, url, title, description, created_at) values (11, 'CSS', 'https://buzzfeed.com/vitae/mattis.xml', 'zero administration', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '1624876948000');
insert into resources (user_id, topic, url, title, description, created_at) values (1, 'Java', 'http://wufoo.com/blandit/mi/in.png', 'multi-state', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', '1565692110000');
insert into resources (user_id, topic, url, title, description, created_at) values (20, 'Python', 'http://prweb.com/morbi/porttitor/lorem.js', 'service-desk', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', '1621581042000');
insert into resources (user_id, topic, url, title, description, created_at) values (5, 'SASS', 'https://spiegel.de/vestibulum/eget.xml', 'multimedia', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '1554190919000');
insert into resources (user_id, topic, url, title, description, created_at) values (5, 'Java', 'https://ehow.com/etiam.js', 'leading edge', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '1575248267000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'JavaScript', 'https://state.gov/pharetra/magna/vestibulum/aliquet.png', 'Progressive', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', '1568715159000');
insert into resources (user_id, topic, url, title, description, created_at) values (18, 'Other', 'http://abc.net.au/condimentum.json', 'paradigm', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '1577527372000');
insert into resources (user_id, topic, url, title, description, created_at) values (14, 'JavaScript', 'https://dyndns.org/lectus/suspendisse/potenti/in.jpg', 'function', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '1614722304000');
insert into resources (user_id, topic, url, title, description, created_at) values (11, 'JavaScript', 'https://dagondesign.com/auctor/sed/tristique/in/tempus.aspx', 'matrix', 'Ut at dolor quis odio consequat varius. Integer ac leo.', '1630735019000');
insert into resources (user_id, topic, url, title, description, created_at) values (7, 'JavaScript', 'https://360.cn/sed/vel/enim/sit/amet.aspx', 'extranet', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', '1574960251000');
insert into resources (user_id, topic, url, title, description, created_at) values (23, 'Python', 'http://xrea.com/mus/etiam/vel.jpg', 'Digitized', 'Donec semper sapien a libero. Nam dui.', '1586334082000');
insert into resources (user_id, topic, url, title, description, created_at) values (19, 'CSS', 'http://nba.com/pharetra/magna/vestibulum/aliquet.jpg', 'asymmetric', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '1641294836000');
insert into resources (user_id, topic, url, title, description, created_at) values (25, 'Python', 'https://tinyurl.com/curabitur/at.html', 'Operative', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '1572462319000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'JavaScript', 'https://smugmug.com/eget/congue/eget/semper/rutrum/nulla.xml', 'Quality-focused', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '1542729225000');
insert into resources (user_id, topic, url, title, description, created_at) values (23, 'Python', 'http://ucla.edu/non/mattis.html', 'capability', 'Fusce consequat. Nulla nisl. Nunc nisl.', '1556822115000');
insert into resources (user_id, topic, url, title, description, created_at) values (12, 'Java', 'https://desdev.cn/eu/interdum/eu/tincidunt/in/leo/maecenas.jsp', 'coherent', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '1600515492000');
insert into resources (user_id, topic, url, title, description, created_at) values (11, 'SASS', 'https://indiatimes.com/in/purus/eu/magna/vulputate/luctus.html', 'user-facing', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '1644522144000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'Java', 'https://wordpress.com/neque/aenean/auctor/gravida/sem/praesent/id.html', 'ability', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', '1627714199000');
insert into resources (user_id, topic, url, title, description, created_at) values (20, 'Python', 'https://mail.ru/tincidunt/nulla/mollis/molestie/lorem/quisque/ut.js', 'moratorium', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '1584858262000');
insert into resources (user_id, topic, url, title, description, created_at) values (12, 'Python', 'https://virginia.edu/quis/augue/luctus.aspx', 'leverage', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', '1560273278000');
insert into resources (user_id, topic, url, title, description, created_at) values (4, 'CSS', 'http://cmu.edu/tellus/nulla.xml', 'workforce', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', '1552273104000');
insert into resources (user_id, topic, url, title, description, created_at) values (3, 'Java', 'https://oracle.com/integer/aliquet/massa.json', 'frame', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '1592351091000');
insert into resources (user_id, topic, url, title, description, created_at) values (3, 'Other', 'http://princeton.edu/consectetuer/adipiscing/elit/proin.html', 'moratorium', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '1545437807000');
insert into resources (user_id, topic, url, title, description, created_at) values (10, 'HTML', 'https://vimeo.com/vestibulum/proin/eu/mi/nulla.js', 'open architecture', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', '1577233823000');
insert into resources (user_id, topic, url, title, description, created_at) values (16, 'Python', 'https://ebay.co.uk/erat/curabitur/gravida/nisi/at/nibh.js', 'Persistent', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', '1597138470000');
insert into resources (user_id, topic, url, title, description, created_at) values (5, 'JavaScript', 'http://sciencedaily.com/pretium/iaculis/diam/erat/fermentum/justo/nec.aspx', 'high-level', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '1573607103000');
insert into resources (user_id, topic, url, title, description, created_at) values (22, 'Python', 'https://gizmodo.com/varius/integer.png', 'Visionary', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', '1627219521000');
insert into resources (user_id, topic, url, title, description, created_at) values (1, 'CSS', 'http://xrea.com/non/mauris/morbi.json', 'human-resource', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '1631944472000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'Python', 'http://quantcast.com/odio/justo/sollicitudin/ut.json', 'model', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '1545347951000');
insert into resources (user_id, topic, url, title, description, created_at) values (17, 'JavaScript', 'http://ox.ac.uk/lacus/purus/aliquet/at/feugiat/non/pretium.js', 'system engine', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', '1572553124000');
insert into resources (user_id, topic, url, title, description, created_at) values (7, 'PHP', 'http://shareasale.com/mauris/morbi/non/lectus/aliquam/sit/amet.json', 'conglomeration', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', '1590918937000');
insert into resources (user_id, topic, url, title, description, created_at) values (9, 'PHP', 'https://theatlantic.com/magnis.json', 'Optimized', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '1575390026000');
insert into resources (user_id, topic, url, title, description, created_at) values (17, 'JavaScript', 'https://icio.us/dapibus/augue.aspx', 'solution-oriented', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '1554375346000');
insert into resources (user_id, topic, url, title, description, created_at) values (19, 'CSS', 'http://fotki.com/in/hac/habitasse/platea/dictumst.xml', '4th generation', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '1629794254000');
insert into resources (user_id, topic, url, title, description, created_at) values (9, 'HTML', 'http://delicious.com/malesuada/in/imperdiet/et/commodo/vulputate.jsp', 'synergy', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '1584353175000');
insert into resources (user_id, topic, url, title, description, created_at) values (2, 'JavaScript', 'http://dropbox.com/lectus/pellentesque/at/nulla/suspendisse.html', 'Fundamental', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '1628658763000');
insert into resources (user_id, topic, url, title, description, created_at) values (24, 'Java', 'http://wisc.edu/in/purus/eu/magna/vulputate.html', 'De-engineered', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '1570367376000');
insert into resources (user_id, topic, url, title, description, created_at) values (20, 'CSS', 'https://columbia.edu/volutpat/erat/quisque/erat/eros/viverra.aspx', 'human-resource', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '1569383419000');
insert into resources (user_id, topic, url, title, description, created_at) values (8, 'HTML', 'http://symantec.com/luctus/et/ultrices/posuere/cubilia/curae.xml', 'concept', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '1589182875000');
insert into resources (user_id, topic, url, title, description, created_at) values (16, 'CSS', 'http://virginia.edu/quisque/ut/erat/curabitur/gravida.html', 'pricing structure', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '1590723736000');
insert into resources (user_id, topic, url, title, description, created_at) values (4, 'Java', 'https://ucoz.ru/at/ipsum.png', 'policy', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '1583885414000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'CSS', 'http://springer.com/integer/tincidunt/ante.png', 'migration', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '1643856544000');
insert into resources (user_id, topic, url, title, description, created_at) values (3, 'SASS', 'http://accuweather.com/at/nulla.json', 'Mandatory', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', '1597401684000');
insert into resources (user_id, topic, url, title, description, created_at) values (23, 'CSS', 'http://tumblr.com/duis.aspx', 'scalable', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '1635286505000');
insert into resources (user_id, topic, url, title, description, created_at) values (24, 'PHP', 'https://npr.org/donec/dapibus/duis/at/velit/eu.xml', 'Ergonomic', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '1623093189000');
insert into resources (user_id, topic, url, title, description, created_at) values (7, 'Python', 'https://msu.edu/dictumst/etiam/faucibus.png', 'local area network', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '1576500100000');
insert into resources (user_id, topic, url, title, description, created_at) values (13, 'PHP', 'https://spotify.com/justo/lacinia/eget/tincidunt.html', 'Vision-oriented', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', '1591744638000');
insert into resources (user_id, topic, url, title, description, created_at) values (18, 'SASS', 'http://goo.ne.jp/faucibus/orci/luctus.xml', 'needs-based', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '1544507396000');
-- test seeds for user_likes
insert into user_likes (resource_id, user_id, liked_at) values (40, 23, '2022-01-29 17:34:05');
insert into user_likes (resource_id, user_id, liked_at) values (9, 8, '2021-02-09 08:33:17');
insert into user_likes (resource_id, user_id, liked_at) values (10, 18, '2019-01-28 22:19:10');
insert into user_likes (resource_id, user_id, liked_at) values (45, 19, '2018-11-02 17:56:29');
insert into user_likes (resource_id, user_id, liked_at) values (42, 22, '2019-07-30 23:14:01');
insert into user_likes (resource_id, user_id, liked_at) values (50, 15, '2018-09-04 02:16:00');
insert into user_likes (resource_id, user_id, liked_at) values (35, 24, '2019-01-15 13:11:22');
insert into user_likes (resource_id, user_id, liked_at) values (45, 23, '2020-07-15 18:53:14');
insert into user_likes (resource_id, user_id, liked_at) values (41, 3, '2020-01-13 15:45:13');
insert into user_likes (resource_id, user_id, liked_at) values (39, 14, '2019-06-09 19:30:14');
insert into user_likes (resource_id, user_id, liked_at) values (2, 7, '2021-07-09 00:52:38');
insert into user_likes (resource_id, user_id, liked_at) values (37, 3, '2022-01-20 23:06:47');
insert into user_likes (resource_id, user_id, liked_at) values (18, 15, '2018-10-28 08:10:53');
insert into user_likes (resource_id, user_id, liked_at) values (36, 1, '2020-11-04 06:42:18');
insert into user_likes (resource_id, user_id, liked_at) values (31, 6, '2019-12-10 03:07:37');
insert into user_likes (resource_id, user_id, liked_at) values (13, 5, '2021-10-17 02:24:58');
insert into user_likes (resource_id, user_id, liked_at) values (3, 16, '2020-11-26 01:23:04');
insert into user_likes (resource_id, user_id, liked_at) values (32, 1, '2019-10-30 22:59:06');
insert into user_likes (resource_id, user_id, liked_at) values (39, 18, '2022-01-12 08:57:20');
insert into user_likes (resource_id, user_id, liked_at) values (46, 7, '2021-04-11 23:06:23');
insert into user_likes (resource_id, user_id, liked_at) values (22, 6, '2018-04-01 09:45:21');
insert into user_likes (resource_id, user_id, liked_at) values (13, 22, '2021-11-09 09:36:16');
insert into user_likes (resource_id, user_id, liked_at) values (30, 6, '2021-06-06 03:02:42');
insert into user_likes (resource_id, user_id, liked_at) values (49, 6, '2019-09-25 22:13:06');
insert into user_likes (resource_id, user_id, liked_at) values (13, 8, '2020-03-28 10:00:17');
insert into user_likes (resource_id, user_id, liked_at) values (32, 7, '2020-01-25 15:41:16');
insert into user_likes (resource_id, user_id, liked_at) values (48, 7, '2021-03-14 09:36:25');
insert into user_likes (resource_id, user_id, liked_at) values (49, 17, '2020-10-20 02:57:49');
insert into user_likes (resource_id, user_id, liked_at) values (27, 3, '2021-04-24 10:28:09');
insert into user_likes (resource_id, user_id, liked_at) values (21, 11, '2018-10-13 09:52:30');
insert into user_likes (resource_id, user_id, liked_at) values (18, 9, '2018-05-23 09:56:52');
insert into user_likes (resource_id, user_id, liked_at) values (23, 19, '2021-10-19 15:06:07');
insert into user_likes (resource_id, user_id, liked_at) values (36, 8, '2019-10-24 13:02:07');
insert into user_likes (resource_id, user_id, liked_at) values (39, 5, '2022-02-01 21:18:34');
insert into user_likes (resource_id, user_id, liked_at) values (20, 3, '2021-10-30 07:40:43');
insert into user_likes (resource_id, user_id, liked_at) values (45, 18, '2018-11-01 18:27:07');
insert into user_likes (resource_id, user_id, liked_at) values (15, 11, '2018-06-21 02:12:42');
insert into user_likes (resource_id, user_id, liked_at) values (38, 16, '2019-09-29 07:14:05');
insert into user_likes (resource_id, user_id, liked_at) values (25, 14, '2020-12-18 21:24:39');
insert into user_likes (resource_id, user_id, liked_at) values (19, 21, '2020-06-27 10:58:32');
insert into user_likes (resource_id, user_id, liked_at) values (4, 13, '2018-02-28 10:17:16');
insert into user_likes (resource_id, user_id, liked_at) values (12, 14, '2018-12-17 10:48:36');
insert into user_likes (resource_id, user_id, liked_at) values (11, 6, '2019-06-17 19:54:08');
insert into user_likes (resource_id, user_id, liked_at) values (17, 13, '2020-05-07 12:02:36');
insert into user_likes (resource_id, user_id, liked_at) values (23, 21, '2021-01-01 07:24:29');
insert into user_likes (resource_id, user_id, liked_at) values (36, 2, '2020-07-27 22:43:33');
insert into user_likes (resource_id, user_id, liked_at) values (11, 10, '2020-03-04 09:41:28');
insert into user_likes (resource_id, user_id, liked_at) values (32, 7, '2018-07-28 11:24:04');
insert into user_likes (resource_id, user_id, liked_at) values (29, 9, '2021-11-15 19:06:37');
insert into user_likes (resource_id, user_id, liked_at) values (44, 10, '2022-02-06 14:44:07');
insert into user_likes (resource_id, user_id, liked_at) values (43, 25, '2020-03-11 05:32:18');
insert into user_likes (resource_id, user_id, liked_at) values (26, 8, '2021-07-01 02:50:13');
insert into user_likes (resource_id, user_id, liked_at) values (26, 14, '2018-03-19 05:52:03');
insert into user_likes (resource_id, user_id, liked_at) values (24, 19, '2020-03-16 12:44:34');
insert into user_likes (resource_id, user_id, liked_at) values (32, 21, '2021-08-31 11:32:38');
insert into user_likes (resource_id, user_id, liked_at) values (27, 23, '2018-10-14 05:39:36');
insert into user_likes (resource_id, user_id, liked_at) values (25, 24, '2018-05-12 07:11:44');
insert into user_likes (resource_id, user_id, liked_at) values (30, 17, '2018-10-11 18:29:48');
insert into user_likes (resource_id, user_id, liked_at) values (9, 21, '2019-05-20 19:05:27');
insert into user_likes (resource_id, user_id, liked_at) values (24, 5, '2021-08-29 10:29:08');
insert into user_likes (resource_id, user_id, liked_at) values (46, 6, '2018-08-05 00:18:23');
insert into user_likes (resource_id, user_id, liked_at) values (9, 12, '2019-09-02 12:51:20');
insert into user_likes (resource_id, user_id, liked_at) values (4, 1, '2019-01-09 14:45:44');
insert into user_likes (resource_id, user_id, liked_at) values (23, 15, '2021-09-03 14:31:49');
insert into user_likes (resource_id, user_id, liked_at) values (42, 1, '2019-04-17 21:47:06');
insert into user_likes (resource_id, user_id, liked_at) values (39, 22, '2018-02-18 16:18:23');
insert into user_likes (resource_id, user_id, liked_at) values (44, 25, '2021-11-13 07:07:05');
insert into user_likes (resource_id, user_id, liked_at) values (25, 11, '2019-05-03 19:18:55');
insert into user_likes (resource_id, user_id, liked_at) values (43, 18, '2021-02-11 17:32:36');
insert into user_likes (resource_id, user_id, liked_at) values (19, 22, '2019-05-31 15:14:19');
insert into user_likes (resource_id, user_id, liked_at) values (5, 9, '2019-04-15 10:06:34');
insert into user_likes (resource_id, user_id, liked_at) values (10, 3, '2018-12-09 13:07:35');
insert into user_likes (resource_id, user_id, liked_at) values (27, 22, '2019-01-16 01:17:54');
insert into user_likes (resource_id, user_id, liked_at) values (11, 14, '2019-07-17 06:30:53');
insert into user_likes (resource_id, user_id, liked_at) values (17, 5, '2018-12-27 08:01:38');
insert into user_likes (resource_id, user_id, liked_at) values (33, 20, '2018-02-14 14:33:27');
insert into user_likes (resource_id, user_id, liked_at) values (25, 3, '2021-10-24 05:46:57');
insert into user_likes (resource_id, user_id, liked_at) values (44, 15, '2019-08-07 17:47:30');
insert into user_likes (resource_id, user_id, liked_at) values (38, 12, '2020-06-24 10:02:44');
insert into user_likes (resource_id, user_id, liked_at) values (25, 6, '2020-01-04 00:42:13');
insert into user_likes (resource_id, user_id, liked_at) values (35, 25, '2020-12-26 00:44:59');
insert into user_likes (resource_id, user_id, liked_at) values (35, 17, '2019-09-13 01:36:28');
insert into user_likes (resource_id, user_id, liked_at) values (16, 19, '2018-07-27 11:21:19');
insert into user_likes (resource_id, user_id, liked_at) values (23, 19, '2021-04-09 23:35:55');
insert into user_likes (resource_id, user_id, liked_at) values (6, 19, '2019-01-30 01:42:49');
insert into user_likes (resource_id, user_id, liked_at) values (47, 16, '2021-01-17 19:03:47');
insert into user_likes (resource_id, user_id, liked_at) values (12, 16, '2019-08-04 19:18:05');
insert into user_likes (resource_id, user_id, liked_at) values (39, 16, '2022-01-27 19:31:55');
insert into user_likes (resource_id, user_id, liked_at) values (25, 6, '2021-09-20 15:54:12');
insert into user_likes (resource_id, user_id, liked_at) values (30, 12, '2018-11-09 21:35:49');
insert into user_likes (resource_id, user_id, liked_at) values (29, 21, '2019-02-19 15:49:50');
insert into user_likes (resource_id, user_id, liked_at) values (43, 15, '2020-07-27 23:00:13');
insert into user_likes (resource_id, user_id, liked_at) values (8, 3, '2021-05-24 13:45:08');
insert into user_likes (resource_id, user_id, liked_at) values (13, 12, '2020-11-12 13:50:47');
insert into user_likes (resource_id, user_id, liked_at) values (37, 12, '2019-01-15 15:17:55');
insert into user_likes (resource_id, user_id, liked_at) values (10, 4, '2018-12-25 16:37:42');
insert into user_likes (resource_id, user_id, liked_at) values (3, 21, '2020-03-10 01:57:43');
insert into user_likes (resource_id, user_id, liked_at) values (27, 4, '2019-08-04 10:15:35');
insert into user_likes (resource_id, user_id, liked_at) values (49, 7, '2020-08-30 19:01:40');
insert into user_likes (resource_id, user_id, liked_at) values (29, 9, '2019-03-12 09:41:48');
-- test seeds for resource_comments
insert into resource_comments (resource_id, user_id, comment, created_at) values (49, 17, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-01-13 14:45:47');
insert into resource_comments (resource_id, user_id, comment, created_at) values (2, 20, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2020-10-17 09:58:44');
insert into resource_comments (resource_id, user_id, comment, created_at) values (19, 19, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2020-07-29 22:44:15');
insert into resource_comments (resource_id, user_id, comment, created_at) values (5, 2, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2020-01-21 14:37:34');
insert into resource_comments (resource_id, user_id, comment, created_at) values (16, 2, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-01-15 08:38:22');
insert into resource_comments (resource_id, user_id, comment, created_at) values (22, 19, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2020-11-13 22:08:39');
insert into resource_comments (resource_id, user_id, comment, created_at) values (48, 20, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2020-12-13 19:16:28');
insert into resource_comments (resource_id, user_id, comment, created_at) values (30, 3, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2018-09-15 03:06:26');
insert into resource_comments (resource_id, user_id, comment, created_at) values (12, 23, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2020-10-15 00:09:17');
insert into resource_comments (resource_id, user_id, comment, created_at) values (27, 7, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2021-07-10 07:08:36');
insert into resource_comments (resource_id, user_id, comment, created_at) values (27, 9, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2021-12-03 02:28:14');
insert into resource_comments (resource_id, user_id, comment, created_at) values (11, 13, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2019-09-27 08:35:21');
insert into resource_comments (resource_id, user_id, comment, created_at) values (42, 22, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2020-01-17 03:57:36');
insert into resource_comments (resource_id, user_id, comment, created_at) values (23, 11, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2019-10-05 03:26:41');
insert into resource_comments (resource_id, user_id, comment, created_at) values (40, 6, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2019-04-07 22:27:43');
insert into resource_comments (resource_id, user_id, comment, created_at) values (38, 18, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2018-10-20 18:06:20');
insert into resource_comments (resource_id, user_id, comment, created_at) values (30, 22, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2019-01-20 06:19:51');
insert into resource_comments (resource_id, user_id, comment, created_at) values (30, 6, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2020-10-05 12:44:28');
insert into resource_comments (resource_id, user_id, comment, created_at) values (19, 8, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2018-04-17 23:37:21');
insert into resource_comments (resource_id, user_id, comment, created_at) values (48, 4, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2019-04-29 05:19:15');
insert into resource_comments (resource_id, user_id, comment, created_at) values (23, 14, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2021-11-14 19:27:36');
insert into resource_comments (resource_id, user_id, comment, created_at) values (40, 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2021-02-06 00:41:52');
insert into resource_comments (resource_id, user_id, comment, created_at) values (19, 12, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-12-30 08:00:04');
insert into resource_comments (resource_id, user_id, comment, created_at) values (14, 9, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2019-01-12 01:38:54');
insert into resource_comments (resource_id, user_id, comment, created_at) values (2, 2, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2020-06-30 05:54:42');
insert into resource_comments (resource_id, user_id, comment, created_at) values (30, 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2021-10-18 22:26:35');
insert into resource_comments (resource_id, user_id, comment, created_at) values (26, 19, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-01-12 08:54:45');
insert into resource_comments (resource_id, user_id, comment, created_at) values (44, 6, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2019-06-05 11:42:19');
insert into resource_comments (resource_id, user_id, comment, created_at) values (48, 11, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2021-04-17 17:31:00');
insert into resource_comments (resource_id, user_id, comment, created_at) values (4, 18, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-10-30 18:08:10');
insert into resource_comments (resource_id, user_id, comment, created_at) values (26, 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2021-07-31 02:35:10');
insert into resource_comments (resource_id, user_id, comment, created_at) values (47, 24, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-02-15 05:30:00');
insert into resource_comments (resource_id, user_id, comment, created_at) values (43, 20, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2019-05-06 07:12:10');
insert into resource_comments (resource_id, user_id, comment, created_at) values (23, 15, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2020-12-18 09:59:31');
insert into resource_comments (resource_id, user_id, comment, created_at) values (22, 8, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2021-09-21 19:26:24');
insert into resource_comments (resource_id, user_id, comment, created_at) values (41, 12, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2019-07-13 22:48:17');
insert into resource_comments (resource_id, user_id, comment, created_at) values (7, 12, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2021-09-17 04:38:07');
insert into resource_comments (resource_id, user_id, comment, created_at) values (12, 12, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2018-12-24 13:04:27');
insert into resource_comments (resource_id, user_id, comment, created_at) values (5, 2, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-06-18 11:44:37');
insert into resource_comments (resource_id, user_id, comment, created_at) values (39, 5, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2018-11-12 04:53:48');
insert into resource_comments (resource_id, user_id, comment, created_at) values (1, 17, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2018-05-31 11:49:09');
insert into resource_comments (resource_id, user_id, comment, created_at) values (37, 20, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2019-05-17 20:06:38');
insert into resource_comments (resource_id, user_id, comment, created_at) values (33, 14, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2021-06-05 08:36:32');
insert into resource_comments (resource_id, user_id, comment, created_at) values (28, 4, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2019-02-18 14:27:55');
insert into resource_comments (resource_id, user_id, comment, created_at) values (38, 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2019-11-01 02:06:57');
insert into resource_comments (resource_id, user_id, comment, created_at) values (7, 8, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2019-10-24 15:25:09');
insert into resource_comments (resource_id, user_id, comment, created_at) values (16, 19, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2021-11-04 16:32:36');
insert into resource_comments (resource_id, user_id, comment, created_at) values (26, 9, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2020-03-31 09:14:58');
insert into resource_comments (resource_id, user_id, comment, created_at) values (5, 3, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2021-01-22 05:26:14');
insert into resource_comments (resource_id, user_id, comment, created_at) values (45, 11, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2021-09-12 22:29:57');
insert into resource_comments (resource_id, user_id, comment, created_at) values (45, 16, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2018-05-07 02:43:57');
insert into resource_comments (resource_id, user_id, comment, created_at) values (49, 19, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2021-03-04 10:49:26');
insert into resource_comments (resource_id, user_id, comment, created_at) values (37, 2, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2021-07-01 17:31:19');
insert into resource_comments (resource_id, user_id, comment, created_at) values (23, 25, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2020-07-22 11:47:13');
insert into resource_comments (resource_id, user_id, comment, created_at) values (48, 10, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2019-02-08 18:08:50');
insert into resource_comments (resource_id, user_id, comment, created_at) values (22, 23, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2019-11-18 22:56:52');
insert into resource_comments (resource_id, user_id, comment, created_at) values (18, 12, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2018-06-23 15:46:29');
insert into resource_comments (resource_id, user_id, comment, created_at) values (16, 23, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-09-03 01:42:31');
insert into resource_comments (resource_id, user_id, comment, created_at) values (42, 3, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2021-11-13 11:59:04');
insert into resource_comments (resource_id, user_id, comment, created_at) values (6, 12, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2019-05-29 02:09:25');
insert into resource_comments (resource_id, user_id, comment, created_at) values (46, 19, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2020-01-16 07:52:54');
insert into resource_comments (resource_id, user_id, comment, created_at) values (36, 20, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2018-03-10 20:51:32');
insert into resource_comments (resource_id, user_id, comment, created_at) values (24, 25, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2019-05-29 09:19:58');
insert into resource_comments (resource_id, user_id, comment, created_at) values (10, 3, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2021-07-21 19:09:44');
insert into resource_comments (resource_id, user_id, comment, created_at) values (21, 2, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2020-04-19 14:43:35');
insert into resource_comments (resource_id, user_id, comment, created_at) values (6, 3, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-02-12 06:54:29');
insert into resource_comments (resource_id, user_id, comment, created_at) values (23, 3, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2018-04-17 19:51:56');
insert into resource_comments (resource_id, user_id, comment, created_at) values (25, 10, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2018-07-16 12:59:07');
insert into resource_comments (resource_id, user_id, comment, created_at) values (24, 25, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2019-10-12 17:24:10');
insert into resource_comments (resource_id, user_id, comment, created_at) values (2, 8, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2019-12-04 20:56:35');
insert into resource_comments (resource_id, user_id, comment, created_at) values (7, 1, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2019-07-09 16:46:17');
insert into resource_comments (resource_id, user_id, comment, created_at) values (43, 25, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2021-01-17 17:09:28');
insert into resource_comments (resource_id, user_id, comment, created_at) values (4, 22, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2018-11-18 03:38:45');
insert into resource_comments (resource_id, user_id, comment, created_at) values (37, 20, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2020-09-25 19:06:52');
insert into resource_comments (resource_id, user_id, comment, created_at) values (32, 4, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-04-07 18:08:16');
insert into resource_comments (resource_id, user_id, comment, created_at) values (6, 2, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2018-07-10 02:48:53');
insert into resource_comments (resource_id, user_id, comment, created_at) values (23, 12, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2019-12-26 08:58:27');
insert into resource_comments (resource_id, user_id, comment, created_at) values (20, 3, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2018-05-27 20:23:49');
insert into resource_comments (resource_id, user_id, comment, created_at) values (37, 14, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-08-09 17:06:33');
insert into resource_comments (resource_id, user_id, comment, created_at) values (20, 15, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2020-01-01 03:16:42');
-- test seeds for ratings
insert into ratings (resource_id, rating) values (10, 3);
insert into ratings (resource_id, rating) values (29, 5);
insert into ratings (resource_id, rating) values (4, 0);
insert into ratings (resource_id, rating) values (7, 2);
insert into ratings (resource_id, rating) values (5, 0);
insert into ratings (resource_id, rating) values (9, 3);
insert into ratings (resource_id, rating) values (50, 4);
insert into ratings (resource_id, rating) values (10, 2);
insert into ratings (resource_id, rating) values (10, 5);
insert into ratings (resource_id, rating) values (19, 3);
insert into ratings (resource_id, rating) values (14, 5);
insert into ratings (resource_id, rating) values (30, 1);
insert into ratings (resource_id, rating) values (21, 3);
insert into ratings (resource_id, rating) values (15, 1);
insert into ratings (resource_id, rating) values (5, 0);
insert into ratings (resource_id, rating) values (47, 4);
insert into ratings (resource_id, rating) values (2, 2);
insert into ratings (resource_id, rating) values (34, 1);
insert into ratings (resource_id, rating) values (38, 4);
insert into ratings (resource_id, rating) values (7, 1);
insert into ratings (resource_id, rating) values (2, 1);
insert into ratings (resource_id, rating) values (29, 5);
insert into ratings (resource_id, rating) values (33, 4);
insert into ratings (resource_id, rating) values (26, 3);
insert into ratings (resource_id, rating) values (45, 1);
insert into ratings (resource_id, rating) values (41, 5);
insert into ratings (resource_id, rating) values (24, 1);
insert into ratings (resource_id, rating) values (33, 3);
insert into ratings (resource_id, rating) values (24, 2);
insert into ratings (resource_id, rating) values (41, 3);
insert into ratings (resource_id, rating) values (41, 4);
insert into ratings (resource_id, rating) values (29, 4);
insert into ratings (resource_id, rating) values (6, 2);
insert into ratings (resource_id, rating) values (33, 1);
insert into ratings (resource_id, rating) values (39, 5);
insert into ratings (resource_id, rating) values (41, 0);
insert into ratings (resource_id, rating) values (11, 2);
insert into ratings (resource_id, rating) values (20, 1);
insert into ratings (resource_id, rating) values (34, 4);
insert into ratings (resource_id, rating) values (11, 2);
insert into ratings (resource_id, rating) values (10, 2);
insert into ratings (resource_id, rating) values (44, 3);
insert into ratings (resource_id, rating) values (46, 0);
insert into ratings (resource_id, rating) values (37, 5);
insert into ratings (resource_id, rating) values (32, 4);
insert into ratings (resource_id, rating) values (19, 5);
insert into ratings (resource_id, rating) values (41, 5);
insert into ratings (resource_id, rating) values (41, 0);
insert into ratings (resource_id, rating) values (9, 5);
insert into ratings (resource_id, rating) values (7, 4);
insert into ratings (resource_id, rating) values (37, 0);
insert into ratings (resource_id, rating) values (43, 3);
insert into ratings (resource_id, rating) values (2, 2);
insert into ratings (resource_id, rating) values (29, 1);
insert into ratings (resource_id, rating) values (31, 2);
insert into ratings (resource_id, rating) values (17, 0);
insert into ratings (resource_id, rating) values (12, 1);
insert into ratings (resource_id, rating) values (47, 3);
insert into ratings (resource_id, rating) values (6, 1);
insert into ratings (resource_id, rating) values (31, 3);
insert into ratings (resource_id, rating) values (16, 2);
insert into ratings (resource_id, rating) values (19, 5);
insert into ratings (resource_id, rating) values (13, 3);
insert into ratings (resource_id, rating) values (50, 3);
insert into ratings (resource_id, rating) values (36, 5);
insert into ratings (resource_id, rating) values (4, 1);
insert into ratings (resource_id, rating) values (46, 1);
insert into ratings (resource_id, rating) values (15, 0);
insert into ratings (resource_id, rating) values (21, 2);
insert into ratings (resource_id, rating) values (50, 2);
insert into ratings (resource_id, rating) values (49, 2);
insert into ratings (resource_id, rating) values (17, 0);
insert into ratings (resource_id, rating) values (14, 3);
insert into ratings (resource_id, rating) values (44, 3);
insert into ratings (resource_id, rating) values (26, 1);
insert into ratings (resource_id, rating) values (31, 0);
insert into ratings (resource_id, rating) values (40, 1);
insert into ratings (resource_id, rating) values (15, 0);
insert into ratings (resource_id, rating) values (28, 0);
insert into ratings (resource_id, rating) values (13, 2);
insert into ratings (resource_id, rating) values (40, 1);
insert into ratings (resource_id, rating) values (19, 4);
insert into ratings (resource_id, rating) values (36, 0);
insert into ratings (resource_id, rating) values (3, 3);
insert into ratings (resource_id, rating) values (41, 1);
insert into ratings (resource_id, rating) values (50, 0);
insert into ratings (resource_id, rating) values (45, 3);
insert into ratings (resource_id, rating) values (34, 1);
insert into ratings (resource_id, rating) values (1, 1);
insert into ratings (resource_id, rating) values (24, 0);
insert into ratings (resource_id, rating) values (5, 1);
insert into ratings (resource_id, rating) values (36, 1);
insert into ratings (resource_id, rating) values (34, 4);
insert into ratings (resource_id, rating) values (32, 1);
insert into ratings (resource_id, rating) values (7, 4);
insert into ratings (resource_id, rating) values (33, 5);
insert into ratings (resource_id, rating) values (44, 1);
insert into ratings (resource_id, rating) values (10, 2);
insert into ratings (resource_id, rating) values (28, 2);
insert into ratings (resource_id, rating) values (50, 4);
insert into ratings (resource_id, rating) values (32, 3);
insert into ratings (resource_id, rating) values (22, 1);
insert into ratings (resource_id, rating) values (3, 3);
insert into ratings (resource_id, rating) values (39, 0);
insert into ratings (resource_id, rating) values (13, 0);
insert into ratings (resource_id, rating) values (18, 4);
insert into ratings (resource_id, rating) values (48, 2);
insert into ratings (resource_id, rating) values (45, 2);
insert into ratings (resource_id, rating) values (37, 2);
insert into ratings (resource_id, rating) values (25, 5);
insert into ratings (resource_id, rating) values (17, 0);
insert into ratings (resource_id, rating) values (12, 5);
insert into ratings (resource_id, rating) values (44, 4);
insert into ratings (resource_id, rating) values (30, 5);
insert into ratings (resource_id, rating) values (3, 2);
insert into ratings (resource_id, rating) values (41, 3);
insert into ratings (resource_id, rating) values (8, 0);
insert into ratings (resource_id, rating) values (40, 4);
insert into ratings (resource_id, rating) values (5, 2);
insert into ratings (resource_id, rating) values (33, 3);
insert into ratings (resource_id, rating) values (23, 2);
insert into ratings (resource_id, rating) values (20, 0);
insert into ratings (resource_id, rating) values (40, 1);
insert into ratings (resource_id, rating) values (3, 1);
insert into ratings (resource_id, rating) values (20, 0);
insert into ratings (resource_id, rating) values (3, 3);
insert into ratings (resource_id, rating) values (47, 4);
insert into ratings (resource_id, rating) values (25, 1);
insert into ratings (resource_id, rating) values (2, 1);
insert into ratings (resource_id, rating) values (34, 2);
insert into ratings (resource_id, rating) values (43, 3);
insert into ratings (resource_id, rating) values (15, 2);
insert into ratings (resource_id, rating) values (24, 1);
insert into ratings (resource_id, rating) values (18, 2);
insert into ratings (resource_id, rating) values (35, 4);
insert into ratings (resource_id, rating) values (34, 4);
insert into ratings (resource_id, rating) values (5, 2);
insert into ratings (resource_id, rating) values (24, 0);
insert into ratings (resource_id, rating) values (34, 2);
insert into ratings (resource_id, rating) values (14, 2);
insert into ratings (resource_id, rating) values (15, 3);
insert into ratings (resource_id, rating) values (3, 2);
insert into ratings (resource_id, rating) values (24, 4);
insert into ratings (resource_id, rating) values (44, 5);
insert into ratings (resource_id, rating) values (36, 0);
insert into ratings (resource_id, rating) values (14, 1);
insert into ratings (resource_id, rating) values (16, 3);
insert into ratings (resource_id, rating) values (40, 3);
insert into ratings (resource_id, rating) values (43, 3);
insert into ratings (resource_id, rating) values (45, 4);
insert into ratings (resource_id, rating) values (25, 3);
insert into ratings (resource_id, rating) values (41, 5);
insert into ratings (resource_id, rating) values (12, 4);
insert into ratings (resource_id, rating) values (15, 0);
insert into ratings (resource_id, rating) values (44, 4);
insert into ratings (resource_id, rating) values (28, 5);
insert into ratings (resource_id, rating) values (50, 0);
insert into ratings (resource_id, rating) values (46, 1);
insert into ratings (resource_id, rating) values (39, 0);
insert into ratings (resource_id, rating) values (6, 1);
insert into ratings (resource_id, rating) values (15, 5);
insert into ratings (resource_id, rating) values (35, 5);
insert into ratings (resource_id, rating) values (36, 0);
insert into ratings (resource_id, rating) values (22, 4);
insert into ratings (resource_id, rating) values (18, 4);
insert into ratings (resource_id, rating) values (11, 5);
insert into ratings (resource_id, rating) values (23, 5);
insert into ratings (resource_id, rating) values (26, 4);
insert into ratings (resource_id, rating) values (22, 1);
insert into ratings (resource_id, rating) values (44, 2);
insert into ratings (resource_id, rating) values (13, 5);
insert into ratings (resource_id, rating) values (3, 4);
insert into ratings (resource_id, rating) values (21, 3);
insert into ratings (resource_id, rating) values (14, 3);
insert into ratings (resource_id, rating) values (7, 3);
insert into ratings (resource_id, rating) values (46, 2);
insert into ratings (resource_id, rating) values (45, 5);
insert into ratings (resource_id, rating) values (30, 2);
insert into ratings (resource_id, rating) values (11, 4);
insert into ratings (resource_id, rating) values (12, 4);
insert into ratings (resource_id, rating) values (29, 2);
insert into ratings (resource_id, rating) values (7, 2);
insert into ratings (resource_id, rating) values (27, 1);
insert into ratings (resource_id, rating) values (9, 3);
insert into ratings (resource_id, rating) values (20, 0);
insert into ratings (resource_id, rating) values (15, 2);
insert into ratings (resource_id, rating) values (47, 4);
insert into ratings (resource_id, rating) values (40, 1);
insert into ratings (resource_id, rating) values (29, 2);
insert into ratings (resource_id, rating) values (7, 5);
insert into ratings (resource_id, rating) values (46, 3);
insert into ratings (resource_id, rating) values (50, 5);
insert into ratings (resource_id, rating) values (36, 3);
insert into ratings (resource_id, rating) values (8, 3);
insert into ratings (resource_id, rating) values (17, 1);
insert into ratings (resource_id, rating) values (7, 0);
insert into ratings (resource_id, rating) values (25, 4);
insert into ratings (resource_id, rating) values (26, 2);
insert into ratings (resource_id, rating) values (12, 0);
insert into ratings (resource_id, rating) values (32, 0);

